server:
  port: ${TOKEN_SERVICE_PORT}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

rsa:
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}

jle:
  host: ${SERVER_HOST}
  api:
    member: ${API_MEMBER_URL}

logging:
  file:
    name: /data/log/token.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 14
      total-size-cap: 1GB
  level:
    root: info